identity:
    build: ./src/identity/
    dockerfile: Dockerfile
    container_name: shopping_identity
    ports:
        - "5004:5004"
    environment:
        - ASPNET_ENV=Development
    links:
        - postgres-identity

listing:
    build: ./src/listing/
    dockerfile: Dockerfile
    container_name: shopping_listing
    ports:
        - "5000:5000"
    environment:
        - ASPNET_ENV=Development

postgres-identity:
    image: postgres
    container_name: shopping_identity_postgres